name: Publish package to hex.pm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish to hex.pm
        uses: wesleimp/action-publish-hex@v1
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
